// Generated by CoffeeScript 1.10.0
(function() {
  var bxCarrousel, cantidad, cantidadCo, checkEasyTabsReheightContents, console, currentStep, f1Value, f2Value, fixFireFoxArrows, fixTablesColombia, goTop, handleAccordion, handleLoadLoginIframe, handleLoadSearchIframe, handleMagazineStepBack, handleMagazineStepForw, handleSliderChange, handleSliderSlide, handleSliderStop, hay_slider, hay_slider_cat, inicial, init, initStepMagazine, isLoadedLogin, isLoadedSearch, renderTables, root, sinModelo, skinNavidad, valCapricho;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  init = function() {
    $('#hslider-content').css('margin-left', 0);
    $('.js-accordion .js-accordion-content').hide();
    $('.js-accordion .js-accordion-title').on('click', handleAccordion);
    $('.prev').hide();
    $('.libro-reclamacion > i').removeClass('icon-chevron-right');
    $('.libro-reclamacion').parent('li').addClass('li-gradient');
    $('.js-home-highlight-close').on('click', handleCloseHomeHighlight);
    $('.js-home-do-highlight-close').on('click', handleCloseHomeDoHighlight);
    $('.js-tienda-highlight-close, .link-tienda-close').on('click', handleCloseTiendaHighlight);
    $('.js-step-magazine .back').on('click', handleMagazineStepBack);
    $('.js-step-magazine .forw').on('click', handleMagazineStepForw);
    $('.menu-login-chile').on('mouseover', handleLoadLoginIframe);
    $('.js-search-iframe').on('click', handleLoadSearchIframe);
    applyReheight();
    goTop();
    renderTables();
    initStepMagazine();
    checkHomeHighlight();
    checkTiendaHighlight();
    checkHomeDoHighlight();
    if ($('#background-highlight').length >= 1) {
      autoCloseHighlight();
    }
    if ($('#background-highlight-1').length >= 1) {
      autoCloseHighlightT();
    }
    if ($('#background-do-highlight').length >= 1) {
      autoCloseDoHighlight();
    }
    fixTablesColombia();
    fixFireFoxArrows();
    $(document).bind('keydown', function(e) {
      if (e.which === 27) {
        return handleCloseHomeDoHighlight();
      }
    });
    $('.panel-showcase.ar .media-container ul.carrusel-catalogo li > img').parent().parent().parent().parent().on('mouseover', function() {
      return $('.panel-showcase.ar .media-container .bx-controls .bx-controls-direction').addClass('capricho');
    });
    $('.panel-showcase.ar .media-container ul.carrusel-catalogo li > img').parent().parent().parent().parent().on('mouseout', function() {
      return $('.panel-showcase.ar .media-container .bx-controls .bx-controls-direction').removeClass('capricho');
    });
    $('#planes-postpago, #recomendados, #miclaro-login-tabs').easytabs({
      animate: true,
      animationSpeed: 100,
      tabActiveClass: 'selected'
    }).bind("easytabs:after", function() {
      var target;
      $('html, body').scrollTop($('#planes-postpago').offset().top);
      if ($('.resumen').length > 0) {
        target = $(this).find('.resumen.active article >div');
        return reheight(target, 'p:nth-of-type(1)', 3);
      }
    });
    $('#promociones-extendido').easytabs({
      animate: true,
      animationSpeed: 100,
      tabActiveClass: 'selected'
    });
    $('#inner-tarifas, #inner-equipos, .js-tab-child').easytabs({
      animate: true,
      animationSpeed: 100,
      tabActiveClass: 'selected',
      updateHash: false
    });
    $('.js-tabEngine').easytabs({
      animate: true,
      animationSpeed: 100,
      tabActiveClass: 'selected',
      updateHash: true
    });
    $('.js-lightbox').fancybox({
      maxWidth: 800,
      maxHeight: 600,
      fitToView: false,
      width: '100%',
      height: '100%',
      autoSize: false,
      closeClick: false,
      openEffect: 'none',
      closeEffect: 'none'
    });
    $('.js-lightbox-detalle').fancybox({
      maxWidth: 990,
      maxHeight: 600,
      fitToView: false,
      width: '100%',
      height: '100%',
      autoSize: false,
      closeClick: false,
      openEffect: 'none',
      closeEffect: 'none'
    });
    $('.js-lightbox-sborde').fancybox({
      fitToView: false,
      autoSize: true,
      closeClick: false,
      openEffect: 'none',
      closeEffect: 'none',
      padding: 0,
      beforeShow: function() {
        return $(".fancybox-skin").css({
          "background": "transparent",
          "box-shadow": "none",
          "-webkit-box-shadow": "none"
        });
      }
    });
    $('.js-lb-asistencia-cl').fancybox({
      maxWidth: 670,
      maxHeight: 495,
      fitToView: false,
      width: '100%',
      height: '100%',
      autoSize: false,
      closeClick: false,
      openEffect: 'none',
      closeEffect: 'none'
    });
    $('.js-lb-solicitar').fancybox({
      maxWidth: 750,
      maxHeight: 600,
      closeClick: false,
      helpers: {
        overlay: {
          closeClick: false
        }
      }
    });
    $('.js-lb-chat-cl').fancybox({
      maxWidth: 460,
      maxHeight: 300
    });
    $('.js-lb').fancybox({
      nextEffect: 'none',
      prevEffect: 'none'
    });
    $('.js-lb-iframe').fancybox({
      type: 'iframe',
      autoSize: true,
      beforeLoad: function() {
        this.width = parseInt(this.element.data('fancybox-width'));
        return this.height = parseInt(this.element.data('fancybox-height'));
      }
    });
    $('.js-iframe-medidas').fancybox({
      type: 'iframe',
      autoSize: false,
      autoResize: true,
      beforeLoad: function() {
        this.width = parseInt(this.element.data('width'));
        return this.height = parseInt(this.element.data('height'));
      }
    });
    $('.js-iframe-cambio-equipos').fancybox({
      type: 'iframe',
      autoSize: false,
      beforeLoad: function() {
        this.width = parseInt(this.element.data('width'));
        return this.height = parseInt(this.element.data('height'));
      },
      beforeShow: function() {
        return $(".fancybox-skin").css({
          "padding": "0px"
        });
      }
    });
    $('.js-iframe-auto').fancybox({
      type: 'iframe',
      autoHeight: true,
      autoWidth: true,
      fitToView: false,
      autoSize: false,
      autoResize: true
    });
    $('.js-iframe-8X6').fancybox({
      type: 'iframe',
      autoHeight: 800,
      autoWidth: 600,
      autoSize: false
    });
    $('.js-lb-planes-precios').fancybox({
      autoSize: true,
      fitToView: true,
      maxWidth: '100%'
    });
    $('.js-splash-lb').fancybox({
      autoSize: true,
      padding: 0,
      fitToView: false,
      beforeShow: function() {
        return $(".fancybox-skin").css({
          "background": "transparent",
          "box-shadow": "none",
          "-webkit-box-shadow": "none"
        });
      }
    });
    $('.js-lb-login').fancybox({
      padding: 0,
      fitToView: false,
      width: 600,
      height: 400,
      beforeShow: function() {
        return $(".fancybox-skin").css({
          "background": "transparent",
          "box-shadow": "none",
          "-webkit-box-shadow": "none"
        });
      }
    });
    $('.js-lb-gallery').fancybox({
      mouseWheel: 'false',
      helpers: {
        thumbs: {
          width: 50,
          height: 50
        },
        title: {
          type: "outside"
        },
        overlay: {
          opacity: 0.6,
          css: {
            "background-color": "rgba(0,0,0,0.8)"
          }
        }
      }
    });
    $('.lb-ytvideo').fancybox({
      openEffect: 'none',
      closeEffect: 'none',
      helpers: {
        media: {}
      }
    });
    $(".lb-multimedia-thumb").fancybox({
      prevEffect: 'none',
      nextEffect: 'none',
      closeBtn: true,
      helpers: {
        title: {
          type: 'float'
        }
      }
    });
    $(".lb-multimedia").fancybox({
      prevEffect: 'none',
      nextEffect: 'none',
      closeBtn: true,
      helpers: {
        title: {
          type: 'float'
        }
      }
    });
    $('.lb-livestream').fancybox({
      type: 'iframe',
      autoHeight: true,
      autoWidth: true
    });
    $('.lb-inline').fancybox({
      type: 'inline',
      autoSize: false,
      beforeLoad: function() {
        this.width = parseInt(this.element.data('width'));
        return this.height = parseInt(this.element.data('height'));
      }
    });
    return $('.filtroAvanzado .buscador .btn-filtroA').on('click', function() {
      var up;
      up = $('.btn-filtroA i.icon-chevron-up').length;
      $('.filtroAvanzado .avanzado').toggle();
      $('.btn-filtroA i').toggleClass('icon-chevron-up');
      return $('.btn-filtroA i').toggleClass('icon-chevron-down');
    });
  };

  $('.js-adicional-card-open').each(function() {
    return $(this).click(function() {
      $(this).parents().eq(4).find('.card .front').fadeToggle();
      $(this).parents().eq(4).find('.card .back').fadeToggle();
      return false;
    });
  });

  $('.js-adicional-card-close').each(function() {
    return $(this).click(function() {
      $(this).parents().eq(4).find('.card .front').fadeToggle();
      $(this).parents().eq(4).find('.card .back').fadeToggle();
      return false;
    });
  });

  $('.js-ip-splash .aside-listing .element').each(function() {
    return $(this).mouseenter(function() {
      var actual;
      actual = $(this).index();
      $('.js-ip-splash .aside-listing .element').removeClass('selected');
      $(this).addClass('selected');
      $('.js-ip-splash .splash-pic li').hide();
      return $('.js-ip-splash .splash-pic li').eq(actual).show();
    });
  });

  $('.recomendados-slider').bxSlider({
    slideWidth: 300,
    minSlides: 3,
    maxSlides: 30,
    moveSlides: 1,
    responsive: true,
    touchEnabled: true,
    slideMargin: 20,
    infiniteLoop: true,
    pager: false
  });

  $('.rotating-banners').bxSlider({
    auto: true,
    slideWidth: 960,
    useCSS: false,
    moveSlides: 1,
    responsive: true,
    touchEnabled: true,
    slideMargin: 0,
    infiniteLoop: true,
    pager: false
  });

  hay_slider = $('.js-carrousel').length;

  if (hay_slider >= 1) {
    bxCarrousel = void 0;
    $(function() {
      return bxCarrousel = $('.js-carrousel').bxSlider({
        slideWidth: 188,
        pager: false,
        minSlides: 5,
        maxSlides: 5,
        moveSlides: 1,
        slideMargin: 0,
        infiniteLoop: false,
        hideControlOnEnd: true,
        onSliderLoad: function() {}
      });
    });
  }

  root.postGalery = function() {
    return $(".carrusel-post-gallery").bxSlider({
      pagerCustom: "#bx-pager",
      useCSS: false,
      auto: true
    });
  };

  root.carruselCatalogo = function() {
    return $(function() {
      return $(".carrusel-catalogo").bxSlider({
        pagerCustom: "#bx-pager",
        useCSS: false
      });
    });
  };

  hay_slider_cat = $('.carrusel-catalogo').length;

  if (hay_slider_cat >= 1) {
    carruselCatalogo();
  }

  $(function() {
    var factor;
    $('#hslider-control').slider({
      animate: 'slow',
      change: handleSliderChange,
      slide: handleSliderSlide,
      stop: handleSliderStop
    });
    factor = ($('#hslider-content >div').width() * $('#hslider-content >div').length) + 24;
    return $('#hslider-content').css('width', factor);
  });

  $('.menu-mapa a').click(function() {
    if ($(this).hasClass('activo')) {
      return $(this).removeClass('activo');
    } else {
      $('.menu-mapa a').removeClass('activo');
      return $(this).addClass('activo');
    }
  });

  $(function() {
    return $('.js-planes, .js-tarifas').slides({
      preload: false,
      slideSpeed: 600,
      generateNextPrev: true
    });
  });

  $(function() {
    return $('.js-slide-table').slides({
      preload: false,
      slideSpeed: 600,
      generatePagination: true,
      generateNextPrev: true
    });
  });

  $(function() {
    return $('#slides-promo').slides({
      effect: 'slide',
      generatePagination: false,
      hoverPause: true,
      pause: 3000,
      play: 5000,
      preload: false,
      preloadImage: 'img/loading.gif'
    });
  });

  $(function() {
    return $('.js-magazine-home').slides({
      preload: false,
      slideSpeed: 600,
      generatePagination: true,
      generateNextPrev: true
    });
  });

  $(function() {
    return $('#slides-videos').slides({
      preload: false,
      slideSpeed: 600,
      generatePagination: false,
      generateNextPrev: true
    });
  });

  $(function() {
    return $('#slides-guia-equipos').slides({
      preload: false,
      slideSpeed: 600,
      generatePagination: false,
      generateNextPrev: true
    });
  });

  $(function() {
    return $('#slides-tablas-promo').slides({
      preload: false,
      slideSpeed: 600,
      generatePagination: false,
      generateNextPrev: true
    });
  });

  $(function() {
    return $('.js-institucional').slides({
      preload: true,
      slideSpeed: 600,
      generatePagination: false,
      generateNextPrev: false
    });
  });

  $(function() {
    return $('.js-ip-social-magazine').slides({
      preload: false,
      generateNextPrev: false
    });
  });

  $(function() {
    return $('#h-magazine-alt').slidesjs({
      width: 47,
      height: 15,
      play: {
        effect: 'slide',
        activate: true,
        interval: 6000,
        auto: true,
        pauseOnHover: false
      }
    });
  });

  $(function() {
    return $('#magazine-primer-co').slidesjs({
      width: 1280,
      height: 360,
      play: {
        effect: 'slide',
        activate: true,
        interval: 6000,
        auto: true,
        pauseOnHover: false
      }
    });
  });


  /*
  $ ->
  	$('#magazine').slidesjs
  		width: 940
  		height: 200
  
  		play:
  			effect: 'slide'
  			activate: true
  			interval: 6000
  			auto: true
  			pauseOnHover: false
   */

  $('#dvMagazineCEQ').show();

  root.sliderCatAr = $('#magazine').bxSlider({
    slideWidth: 940,
    useCSS: false,
    auto: true,
    pause: 6000,
    hideControlOnEnd: true,
    captions: true,
    controls: true
  });

  root.reactSlider = function() {
    $('#dvMagazineCEQ').show();
    return sliderCatAr.reloadSlider();
  };

  $(function() {
    return $('#magazine-catalogo').slidesjs({
      width: 700,
      height: 150,
      play: {
        effect: 'slide',
        activate: true,
        interval: 6000,
        auto: true,
        pauseOnHover: false
      }
    });
  });

  $(function() {
    return $('#magazine-segundo').slidesjs({
      width: 940,
      height: 300,
      play: {
        effect: 'slide',
        activate: true,
        interval: 6000,
        auto: true,
        pauseOnHover: false
      }
    });
  });

  $(function() {
    return $('.js-dateselector-sala').datepicker({
      changeMonth: true,
      changeYear: true,
      yearRange: '2014:2014',
      showOn: "button",
      buttonImage: "css/img/calendar.gif"
    }, $.datepicker.regional["es"]);
  });

  $(function() {
    $('.js-dateselector-today').datepicker({
      changeMonth: true,
      changeYear: true,
      yearRange: '1940:2014',
      maxDate: '+0D'
    }, $.datepicker.regional["es"]);
    $('.js-dateselector-today').datepicker({
      onClose: function() {
        return this.focus();
      }
    });
    return $('.js-dateselector-today').datepicker({
      onSelect: function() {
        return this.focus();
      }
    });
  });

  $(function() {
    $('.js-dateselector-inst').datepicker({
      changeMonth: true,
      changeYear: true,
      yearRange: '2010:2015',
      maxDate: '+0D'
    }, $.datepicker.regional["es"]);
    $('.js-dateselector-inst').datepicker({
      onClose: function() {
        return this.focus();
      }
    });
    return $('.js-dateselector-inst').datepicker({
      onSelect: function() {
        return this.focus();
      }
    });
  });

  $(function() {
    $('.js-dateselector-future').datepicker({
      changeMonth: true,
      changeYear: true,
      yearRange: '2012:2030'
    }, $.datepicker.regional["es"]);
    $('.js-dateselector-future').datepicker({
      onClose: function() {
        return this.focus();
      }
    });
    return $('.js-dateselector-future').datepicker({
      onSelect: function() {
        return this.focus();
      }
    });
  });

  $(function() {
    root.dClic = function() {
      return $('.slidesjs-slide').each(function(index) {
        if ($('.dubleClic').eq(index).children('a').length <= 1) {
          $('.dubleClic').eq(index).children('a').width('100%');
        }
        if ($('.dubleClic').eq(index).children('a').length >= 2) {
          return $(this).eq(index).children('a').width('50%');
        }
      });
    };
    root.rh25 = $('.dubleClic').length;
    if (rh25 >= 1) {
      return dClic();
    }
  });

  jQuery(function($) {
    $.datepicker.regional["es"] = {
      closeText: "Cerrar",
      prevText: "&#x3c;Ant",
      nextText: "Sig&#x3e;",
      currentText: "Hoy",
      monthNames: ["Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"],
      monthNamesShort: ["Ene", "Feb", "Mar", "Abr", "May", "Jun", "Jul", "Ago", "Sep", "Oct", "Nov", "Dic"],
      dayNames: ["Domingo", "Lunes", "Martes", "Mi&eacute;rcoles", "Jueves", "Viernes", "S&aacute;bado"],
      dayNamesShort: ["Dom", "Lun", "Mar", "Mi&eacute;", "Juv", "Vie", "S&aacute;b"],
      dayNamesMin: ["Do", "Lu", "Ma", "Mi", "Ju", "Vi", "S&aacute;"],
      weekHeader: "Sm",
      dateFormat: "dd/mm/yy",
      firstDay: 1,
      isRTL: false,
      showMonthAfterYear: false,
      yearSuffix: ""
    };
    return $.datepicker.setDefaults($.datepicker.regional["es"]);
  });

  inicial = 0;

  root.couter = function() {
    return inicial = inicial + 1;
  };

  root.autoCloseHighlight = function() {
    return setTimeout((function() {
      return handleCloseHomeHighlight();
    }), 12000);
  };

  root.autoCloseHighlightT = function() {
    return setTimeout((function() {
      return handleCloseTiendaHighlight();
    }), 12000);
  };

  root.autoCloseDoHighlight = function() {
    return setTimeout((function() {
      return handleCloseHomeDoHighlight();
    }), 32000);
  };

  handleSliderChange = function(e, ui) {
    var offset, position;
    offset = (($('#hslider-content').width()) - 940) / 100;
    position = ui.value;
    $('#hslider-content').css('margin-left', -(position * offset));
    if (position > 3) {
      $('.fader-l').fadeIn();
      $('.fader-r').fadeIn();
    } else {
      $('.fader-l').fadeOut();
      $('.fader-r').fadeOut();
    }
    if (position > 97) {
      $('.fader-r').fadeOut();
    }
  };

  handleSliderSlide = function(e, ui) {
    var offset, position;
    offset = ($('#hslider-content').width() - 940) / 100;
    position = ui.value;
    $('#hslider-content').css('margin-left', -(position * offset));
  };

  handleSliderStop = function(e, ui) {
    var newposition;
    newposition = $('#hslider-content').attr('style');
  };

  root.handleCloseHomeHighlight = function() {
    $('#background-highlight').fadeOut();
    $.cookie('statusHomeHighlight', 'close', {
      expires: 1,
      path: "/"
    });
  };

  root.handleCloseTiendaHighlight = function() {
    $('#background-highlight-1').fadeOut();
    $.cookie('statusTiendaHighlight', 'close', {
      expires: 1,
      path: "/"
    });
  };

  root.handleCloseHomeDoHighlight = function() {
    $('#background-do-highlight').fadeOut();

    /*
    	$.cookie 'statusHomeDoHighlight', 'close',
    		expires: 1
    		path: "/"
     */
  };

  handleAccordion = function() {
    $('.js-accordion-content').slideUp();
    $('.js-accordion-title i').attr('class', 'icon-chevron-down');
    $(this).parents().eq(1).find('i').toggleClass('icon-chevron-down').toggleClass('icon-chevron-up');
    if (!$(this).parents().eq(1).find('.js-accordion-content').is(":hidden")) {
      $(this).parents().eq(1).find('i').toggleClass('icon-chevron-down').toggleClass('icon-chevron-up');
    }
    if (!$(this).parents().eq(1).find('.js-accordion-content').is(":visible")) {
      $(this).parents().eq(1).find('.js-accordion-content').slideDown('fast');
    }
  };

  isLoadedLogin = false;

  handleLoadLoginIframe = function() {
    var htmlContent;
    if (!isLoadedLogin) {
      htmlContent = "<iframe src=\"https://sucursalvirtual.clarochile.cl/sucursal/login\" frameborder=\"0\" width=\"250\" scrolling=\"no\" height=\"140\"></iframe>";
      $(".js-menu-login-iframe").html(htmlContent);
      return isLoadedLogin = true;
    }
  };

  isLoadedSearch = false;

  handleLoadSearchIframe = function() {
    var htmlContent;
    if (!isLoadedSearch) {
      htmlContent = "<iframe src=\"http:\/\/clarochile.custhelp.com\/app\/search\" allowtransparency=\"allowtransparency\" frameborder=\"0\" height=\"40\" scrolling=\"no\" width=\"400\"><\/iframe>";
      $('.js-search-iframe').html(htmlContent);
      return isLoadedSearch = true;
    }
  };

  root.checkHomeHighlight = function() {
    if (!$.cookie('statusHomeHighlight')) {
      return $('#background-highlight').fadeIn();
    }
  };

  root.checkTiendaHighlight = function() {
    if (!$.cookie('statusTiendaHighlight')) {
      return $('#background-highlight-1').fadeIn();
    }
  };

  root.checkHomeDoHighlight = function() {
    if (!$.cookie('statusHomeDoHighlight')) {
      return $('#background-do-highlight').fadeIn();
    }
  };

  root.applyReheight = function() {
    reheight($('#actions'), "h3", 4);
    reheight($('#actions'), "p", 4);
    reheight($('#complementarios section >div article >div'), "p:nth-of-type(1)", 3);
    reheight($('#complementarios section >div article >div'), "p:nth-of-type(2)", 3);
    reheight($('#bigfooter >div >section'), "div", 6);
    reheight($('#features'), "h3", 4);
    reheight($('#features'), "p", 4);
    reheight($('#destacados'), "h3", 3);
    reheight($('#destacados'), "p", 3);
    reheight($('#ayuda-masconsultado'), "dl", 3);
    reheight($('#ayuda-accesos'), "h3", 4);
    reheight($('#ayuda-accesos'), "p", 4);
    reheight($('#paquetes'), "h3", 3);
    reheight($('#paquetes'), "p", 3);
    reheight($('.panel-galeria >div'), "p", 4);
    reheight($('#h-legal'), "p", 3);
    reheight($('#h-legal'), "h3", 3);
    reheight($('.cc-extra .container >div'), "p", 3);
    reheight($('.cc-extra .container >div'), "h4", 3);
    reheight($('.adicional .container article table tbody'), "p", 3);
    reheight($('.panel-comunicados'), "p", 3);
    reheight($('#magazine-institucional'), ".g2 p", 6);
    reheight($('.panel-tri-info'), '.desc', 3);
  };

  fixTablesColombia = function() {
    $(".tablaColombia").removeAttr("style").removeAttr("color").removeAttr("width");
    $(".tablaColombia td").removeAttr("width");
    $(".tablaColombia thead").removeAttr("style");
    $(".tablaColombia tbody").removeAttr("style");
    $(".tablaColombia span").removeAttr("style");
    $(".tablaColombia td").removeAttr("nowrap");
    return $(".tablaColombia p").removeAttr("align");
  };

  fixFireFoxArrows = function() {
    var is_firefox;
    is_firefox = /firefox/i.test(navigator.userAgent);
    if (is_firefox) {
      return $('.menuSelector-left >li >a').addClass('cancel-arrow');
    }
  };

  root.reheight = function(target, what, interval) {
    var arrMul, arrUni, cont, howmany, i, j, newValue, x;
    arrUni = new Array();
    target = target.find(what);
    howmany = target.length;
    i = 0;
    while (i < howmany) {
      target.eq(i).removeAttr('style');
      arrUni.push(parseInt(target.eq(i).height()));
      i++;
    }
    arrMul = new Array();
    cont = Math.ceil(arrUni.length / interval);
    i = 0;
    x = 0;
    while (i < cont) {
      arrMul[i] = arrUni.slice(i * interval, (i * interval) + interval);
      arrMul[i].sort(function(a, b) {
        return a - b;
      });
      arrMul[i].reverse();
      newValue = arrMul[i][0];
      j = 0;
      while (j < interval) {
        target.eq(x).css('height', newValue);
        x++;
        j++;
      }
      i++;
    }
  };

  goTop = function() {
    setTimeout((function() {
      $(window).scrollTop(0);
      return checkEasyTabsReheightContents();
    }), 100);
  };

  checkEasyTabsReheightContents = function() {
    var target;
    if ($('.resumen').length > 0) {
      target = $('.resumen.active article >div');
      return reheight(target, 'p:nth-of-type(1)', 3);
    }
  };

  renderTables = function() {
    var howManyPlanSelectors, s;
    $('.planes-region .planes-elemento').hide();
    $('.planes-region').find('.planes-elemento:first-child').show();
    howManyPlanSelectors = $('.js-plan-selector').length;
    s = 0;
    while (s < howManyPlanSelectors) {
      $('.js-plan-selector').eq(s).attr('name', s);
      s++;
    }
    $('.js-plan-selector').each(function() {
      return $(this).change(function() {
        var context, element;
        context = parseInt($(this).attr('name'));
        element = $(this)[0].selectedIndex;
        $('.planes-region').eq(context).find('.planes-elemento').hide();
        return $('.planes-region').eq(context).find('.planes-elemento').eq(element).show();
      });
    });
  };

  initStepMagazine = function() {
    var howlarge, howmany;
    $('.js-step-magazine .back').hide();
    howmany = $('.js-step-magazine .element').length;
    howlarge = $('.js-step-magazine .element').width();
    return $('.js-step-magazine .element-wrapper').css('width', howlarge * howmany + 'px');
  };

  currentStep = 0;

  handleMagazineStepBack = function() {
    var stepSize;
    $('.js-step-magazine .forw').fadeIn();
    stepSize = $('.js-step-magazine .element').width();
    currentStep -= stepSize;
    $('.js-step-magazine .element-wrapper').animate({
      marginLeft: '-' + currentStep + 'px'
    }, function() {
      if (currentStep <= 0) {
        $('.js-step-magazine .back').hide();
        return $('.js-step-magazine .element-wrapper').css('margin-left', 0);
      }
    });
    return false;
  };

  handleMagazineStepForw = function() {
    var elementWrapperWidth, factor, howlarge, howlargeWrap, howmany, stepSize;
    howmany = $('.js-step-magazine .element').length;
    howlarge = $('.js-step-magazine .element').width();
    howlargeWrap = $('.js-step-magazine .wrapper').width();
    factor = 6;
    elementWrapperWidth = howmany * howlarge;
    $('.js-step-magazine .back').fadeIn();
    stepSize = $('.js-step-magazine .element').width();
    currentStep += stepSize;
    $('.js-step-magazine .element-wrapper').animate({
      marginLeft: '-' + currentStep + 'px'
    }, function() {
      if (currentStep >= elementWrapperWidth - (factor * howlarge)) {
        return $('.js-step-magazine .forw').hide();
      }
    });
    return false;
  };

  root.jQuery.fn.reset = function() {
    return $(this).each(function() {
      return this.reset();
    });
  };

  root.openComunas = function() {
    $.fancybox.open("#lb-comunas");
  };

  cantidad = void 0;

  sinModelo = 0;

  root.encuentraPlan = function() {
    $(".js-tab-result").hide();
    cantidad = void 0;
    sinModelo = 0;
    $(".contenPreguntas fieldset .selector > li").on("click", function() {
      var val1, val2, val3, valNo;
      $(this).parent().children("li").removeClass("selected");
      $(this).addClass("selected");
      val1 = $(".contenPreguntas fieldset .selector:eq(0) li.selected").length;
      val2 = $(".contenPreguntas fieldset .selector:eq(1) li.selected").length;
      val3 = $(".contenPreguntas fieldset .selector:eq(2) li.selected").length;
      valNo = $(".contenPreguntas fieldset .selector:eq(0) li:eq(3).selected").length;
      if (valNo === 1) {
        if (sinModelo === 1) {

        } else if (sinModelo === 0) {
          $(".toolPreg").show();
        }
      } else if (valNo === 0) {
        $(".toolPreg").hide();
      }
      if ((val1 === 1) && (val2 === 1) && (val3 === 1)) {
        cantidad = 1;
        $(".encontrar").removeClass("btn-gris");
        $(".notificacion").hide();
        setTimeout(reEncuentra, 300);
        return;
      } else {
        cantidad = 0;
      }
    });
    $(".encontrar").on("click", function(e) {
      e.preventDefault();
      if (cantidad === 1) {
        $(".js-tab-encuentraPlan").hide();
        $(".js-tab-result").show();
        $(".notificacion").hide();
      } else {
        $(".notificacion").show();
      }
    });
    $("a.no").on("click", function(e) {
      e.preventDefault();
      sinModelo = 1;
      $(".toolPreg").hide();
    });
  };

  cantidadCo = void 0;

  f1Value = void 0;

  f2Value = void 0;

  root.encuentraPlanCo = function() {
    $(".js-tab-result").hide();
    cantidadCo = void 0;
    $(".contenPreguntas fieldset .selector > li").on("click", function() {
      var selected, selectedCat, val1;
      $(this).parent().children("li").removeClass("selected");
      $(this).addClass("selected");
      selected = $(this).data('valor');
      selectedCat = $(this).data('cat');
      if (selectedCat === 'servicio') {
        $(".contenPreguntas fieldset").show();
        $(".contenPreguntas fieldset:eq(5), .contenPreguntas fieldset:eq(6)").hide();
        $('.contenPreguntas fieldset:eq(1) .selector li, .contenPreguntas fieldset:eq(2) .selector li, .contenPreguntas fieldset:eq(3) .selector li, .contenPreguntas fieldset:eq(4) .selector li, .contenPreguntas fieldset:eq(5) .selector li, contenPreguntas fieldset:eq(6) .selector li').removeClass("selected");
        f1Value = $(this).data('valor');
        if (f1Value === 'voz') {
          $('.filtro2 .selector li').show();
          $('.contenPreguntas fieldset .selector:eq(1) li:eq(3)').hide();
          $('.contenPreguntas fieldset:eq(3)').hide();
        } else if (f1Value === 'voz_datos') {
          $('.filtro2 .selector li').show();
          $('.contenPreguntas fieldset .selector:eq(1) li:eq(3), .contenPreguntas fieldset .selector:eq(1) li:eq(4)').hide();
        } else {
          $('.filtro2 .selector li').show();
          $('.contenPreguntas fieldset .selector:eq(1) li:eq(4)').hide();
          $('.contenPreguntas fieldset:eq(4), .contenPreguntas fieldset:eq(5)').hide();
        }
      }
      if (selectedCat === 'tiempo') {
        f2Value = $(this).data('valor');
        if (f2Value === 'mins') {
          $('.contenPreguntas fieldset:eq(5)').show();
          $('.contenPreguntas fieldset:eq(6)').hide();
        } else if (f2Value === 'segs') {
          $('.contenPreguntas fieldset:eq(5)').hide();
          $('.contenPreguntas fieldset:eq(6)').show();
        }
      }
      val1 = $(".contenPreguntas fieldset .selector:eq(0) li.selected").length;
      if (val1 === 1) {
        cantidadCo = 1;
        $(".encontrar").removeClass("btn-gris");
        $(".notificacion").hide();
        setTimeout(reEncuentra, 300);
        return;
      } else {
        cantidadCo = 0;
        $(".encontrar").addClass("btn-gris");
      }
    });
    $(".encontrar").on("click", function(e) {
      e.preventDefault();
      if (cantidadCo === 1) {
        $(".js-tab-encuentraPlan").hide();
        $(".js-tab-result").show();
        $(".notificacion").hide();
        $(".filtro2, .filtro3, .filtro4, .filtro5, .filtro6").hide();
      } else {
        $(".notificacion").show();
      }
    });
  };

  root.reEncuentra = function() {
    return $(".reEncuentra").on("click", function(e) {
      e.preventDefault();
      $(".js-tab-encuentraPlan, .contenPreguntas").show();
      $(".js-tab-result").hide();
      $(".contenPreguntas fieldset .selector li").removeClass("selected");
      $(".encontrar").addClass("btn-gris");
      cantidad = 0;
      cantidadCo = 0;
      sinModelo = 0;
    });
  };

  root.cajetin = function() {
    $('.nav-bar-right .menu-item-li:last-child').addClass('hover');
    $('.menuSelector .menuSelector-right > li:last-child').addClass('hover');
  };

  root.mod_accordeon = function() {
    var $this;
    $this = $(this);
    $this.toggleClass("uncolapse");
    if ($this.is(".uncolapse")) {
      if ($this.children(".com-paquete-acor").children(".elem-btn").children("i").hasClass("icon-plus")) {
        $this.children(".com-paquete-acor").children(".elem-btn").children("i").addClass("icon-remove").removeClass("icon-plus");
      } else {
        $this.children(".com-paquete-acor").children(".elem-btn").children("i").addClass("icon-chevron-up").removeClass("icon-chevron-down");
      }
      $this.parent().children("dd").slideDown();
    } else {
      if ($this.children(".com-paquete-acor").children(".elem-btn").children("i").hasClass("icon-remove")) {
        $this.children(".com-paquete-acor").children(".elem-btn").children("i").addClass("icon-plus").removeClass("icon-remove");
      } else {
        $this.children(".com-paquete-acor").children(".elem-btn").children("i").addClass("icon-chevron-down").removeClass("icon-chevron-up");
      }
      $this.parent().children("dd").slideUp();
    }
  };

  $(".mod-paquetes-tarifas dl dt").on("click", mod_accordeon);

  $(".mod-paquetes-tarifas dl dt .elem-act .link, .mod-paquetes-tarifas dl dt .elem-pais .link, .mod-paquetes-tarifas dl dt .elem-can .link, .mod-paquetes-tarifas dl dt .elem-btr .btn-rojo").on("click", function(e) {
    var $this, link, targ;
    e.stopPropagation();
    $this = $(this);
    link = $this.attr("href");
    targ = $this.attr("target");
    if (targ.length >= 1) {
      location.target = targ;
    } else {
      location.href = link;
    }
  });

  $('.mod-paquetes-tarifas .cerrar').on('click', function(e) {
    e.preventDefault();
    return $(this).parent().parent().parent().parent().children('dt').trigger('click');
  });

  root.ajustar1 = function(ruta) {
    var altura, i, maxHeight, total;
    $(ruta).removeAttr('style', 'height');
    altura = [];
    total = $(ruta).length - 1;
    i = 0;
    while (i <= total) {
      altura.push($(ruta).eq(i).height());
      i++;
    }
    maxHeight = Math.max.apply(null, altura);
    $(ruta).height(maxHeight);
  };

  root.promoBlock = function() {
    $('.plan-promo-block .first').removeAttr('style');
    return ajustar1('.plan-promo-block .first');
  };

  valCapricho = $('#planes-postpago .plan-promo-block').length;

  if (valCapricho >= 1) {
    $('.menutab-red li').on('click', function() {
      setTimeout(promoBlock, 150);
    });
  }

  $(window).on('load', function() {
    var alto, sochi;
    if ($('.plan-promo-block .first').length >= 1) {
      $('.plan-promo-block .first').removeAttr('style');
      ajustar1('.plan-promo-block .first');
    }
    alto = $('body').height() - 953;
    sochi = $('#floating-sochi-left').length;
    if (sochi >= 1) {
      $('#floating-sochi-left').css('bottom', -alto);
    }
    postGalery();
    return applyReheight();
  });

  root.decoAlert = function(alerta) {
    $('body').append('<div id="alert-Deco"><p>');
    $('#alert-Deco p').text(alerta);
    return $.fancybox.open({
      href: '#alert-Deco',
      width: '300',
      height: '100',
      autoSize: false
    });
  };

  root.preLoader = function(valor) {
    valor = valor;
    if (valor === 0) {
      return $('body').append('<div class="preloaderFun" style="position: fixed; width:100%; height:100%; background:rgba(0,0,0,0.5); top:0px; left:0px; z-index:100;"><div style="width:100px; height: 100px; position: absolute; top: 50%;  left:50%; margin-top:-50px; margin-left:-50px; color: white; font-size: 3em;"><i class="icon-spinner icon-spin icon-large"></i></div></div>');
    } else if (valor === 1) {
      return $('.preloaderFun').remove();
    }
  };

  $.each($('.tooltip'), function(index) {
    var elTooltip, sinTooltip;
    elTooltip = function() {
      var arriba, izquierda, sinTooltip, texto;
      arriba = void 0;
      izquierda = void 0;
      texto = void 0;
      elTooltip = void 0;
      sinTooltip = void 0;
      return $(this).mousemove(function(e) {
        arriba = e.pageY;
        izquierda = e.pageX;
        izquierda = izquierda(+16);
        texto = $(this).data('tooltip');
        $('.tooltipText').css({
          top: arriba,
          left: izquierda
        });
        if ($('.tooltipText').is(':visible')) {

        } else {
          $('.standard').append('<div class="tooltipText">' + texto + '</div>');
        }
      });
    };
    sinTooltip = function() {
      $('.tooltipText').remove();
    };
    $(this).on('mouseenter', elTooltip);
    $(this).on('mouseleave', sinTooltip);
  });

  skinNavidad = '#floating-navidad-left, #floating-navidad-right, #floating-navidad-verano-left, #floating-navidad-verano-right'.length;

  root.anchoNavidad = function() {
    var ancho, maxAncho;
    maxAncho = 1100;
    ancho = $(window).innerWidth();
    if (ancho <= (maxAncho - 1)) {
      $('#floating-navidad-left, #floating-navidad-right, #floating-navidad-verano-left, #floating-navidad-verano-right').hide();
    } else if (ancho >= maxAncho) {
      $('#floating-navidad-left, #floating-navidad-right, #floating-navidad-verano-left, #floating-navidad-verano-right').show();
    }
  };

  root.verPromo = function() {
    $('.planPromo span.btn-rojo').off('click');
    return $('.planPromo span.btn-rojo').on('click', function() {
      var $this, action, altura, footer, grid, parentIndex, visible;
      action = 0;
      grid = 0;
      footer = 0;
      $this = $(this);
      $($this).parent().children('.promoView').toggleClass('visible');
      parentIndex = $($this).parent().parent().index();
      action = $('.plan-element:eq(' + parentIndex + ') .plan-price-action').innerHeight();
      grid = $('.plan-element:eq(' + parentIndex + ') .plan-grid').innerHeight();
      footer = $('.plan-element:eq(' + parentIndex + ') .plan-footer').innerHeight();
      altura = action + grid + footer + 6;
      console.log(parentIndex + ' ' + action + ' ' + grid + ' ' + footer + ' ' + altura);
      visible = $($this).parent().children('.promoView').hasClass('visible');
      switch (visible) {
        case true:
          $($this).parent().children('.promoView').height(altura);
          $($this).html('Cerrar<i class="icon-chevron-down"></i>');
          break;
        case false:
          $($this).parent().children('.promoView').height(0);
          $($this).html('Ver promoción<i class="icon-chevron-up"></i>');
      }
    });
  };

  root.textDin = function() {
    $('.top-bar .top-bar-left a:contains("Claro video"), .top-bar .top-bar-left a:contains("Claro música"), .top-bar .top-bar-left a:contains("Claro musica"), .top-bar .top-bar-left a:contains("Claro play") ').css({
      'font-family': 'din',
      'font-size': '14px'
    });
  };

  root.rotateBanners = function(elem) {
    var active, next;
    active = $(elem + ' .rb.active');
    next = active.next();
    if (next.length === 0) {
      next = $(elem + ' .rb:first');
    }
    active.removeClass('active').fadeOut(200);
    next.addClass('active').fadeIn(200);
  };

  root.prepareRotator = function(elem) {
    $(elem + ' .rb').fadeOut(0);
    $(elem + ' .rb:first').fadeIn(0).addClass('active');
  };

  root.startRotator = function(elem, time) {
    prepareRotator(elem);
    setInterval('rotateBanners(\'' + elem + '\')', time);
  };

  root.prevImage = function(elem) {
    var active, prev;
    active = $(elem + ' .rb.active');
    prev = active.prev();
    if (prev.length === 0) {
      prev = $(elem + ' .rb:first');
    }
    active.removeClass('active').fadeOut(200);
    return prev.addClass('active').fadeIn(200);
  };

  $(document).on('ready', init);

  if (skinNavidad >= 1) {
    anchoNavidad();
    $(window).on('resize', anchoNavidad);
  }

  $(window).on('hashchange', function() {
    return setTimeout(applyReheight, 100);
  });

  root.elAutoajusta = function() {
    var alt, total;
    ajustar1(".plan-tabla.first");
    total = $('.plan-tabla.first').height();
    alt = ($('.plan-tabla.first').height()) + 30;
    if ($('.js-slide-table').length >= 1) {
      $('.js-slide-table > div').height(alt);
      if ($('.js-slide-table').height() <= 20) {
        $('.js-slide-table > div').height(alt);
      }
    }
  };

  if ($(".plan-tabla.first").length >= 1) {
    setTimeout((function() {
      elAutoajusta();
      return $(".menutab-red li a, .js-tab-child li a, .js-AjustaAltura, .link").on("click", function() {
        setTimeout(elAutoajusta, 300);
        return setTimeout(applyReheight, 100);
      });
    }), 310);
    $(window).on('hashchange', function() {
      setTimeout(elAutoajusta, 300);
      return setTimeout(applyReheight, 100);
    });
  }

  console = console;

  if (typeof console === 'undefined' || typeof console.log === 'undefined') {
    console = {};
    console.log = function() {};
  }

  verPromo();

  textDin();

}).call(this);
